### ISSUE TITLE
Make partial views Shadow DOM v1 ready 

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#74]
@tomalec I saw you made PRs is few apps to migrate views to Shadow DOM v1. I have a problem to do that in surfaces in this app:

https://github.com/StarcounterApps/Website/tree/develop/src/Website/wwwroot/Website/templates

Could you pls help?

**Comment by tomalec** [comment]
Could we assume V1 support => CSS Grid Layout support?

supporting this
```css
            /* For browsers w/o Grid break SD boundary and add gutter as margin */
            @supports( not ((display: grid) and (grid-column-gap: 5px)) ) {
                .website-defaulttemplate-topbar ::content > starcounter-include > juicy-composition > *,
                .website-defaulttemplate-topbar ::content > starcounter-include > juicy-composition > starcounter-include > juicy-composition > *,
                /*
                 Shadow DOM v1 in-compatible Shadow DOM piercing selector
                 styling such things may break default compositions delivered by apps
                */
                .website-defaulttemplate-topbar ::content > starcounter-include > juicy-composition::shadow>*,
                .website-defaulttemplate-topbar ::content > starcounter-include > juicy-composition > starcounter-include > juicy-composition::shadow>* {
                    margin-right: 5px;
                }
```
in V1 will not be possible without serious JS hacks.

And still supporting even `.website-defaulttemplate-topbar ::content > starcounter-include > juicy-composition > starcounter-include > juicy-composition` (which looks smelly and liek a bad design) without touching the light DOM and HTML structure may not be possible.
